# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilePicture',
            field=models.ImageField(null=True, upload_to=b'', verbose_name=b'pictures/profile/%Y/%m/%d'),
        ),
    ]
