# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-19 16:25
from __future__ import unicode_literals

import aberdeengo.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', aberdeengo.models.CustomUserManager()),
            ],
        ),
    ]
