# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0002_event_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='range',
            field=models.IntegerField(default=3),
        ),
    ]
