# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0002_customuser_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('num_events', models.IntegerField()),
                ('num_attended', models.IntegerField()),
                ('num_active', models.IntegerField()),
                ('most_attended', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.Event')),
            ],
        ),
        migrations.CreateModel(
            name='TagSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
