# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0003_auto_20170204_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='tags',
            field=models.ManyToManyField(to='aberdeengo.Tag'),
        ),
    ]
