# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-20 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0003_auto_20170320_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='range',
            field=models.IntegerField(default=0),
        ),
    ]
