# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0003_eventsummary_summary_tagsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsummary',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.Event'),
        ),
        migrations.AddField(
            model_name='eventsummary',
            name='num_attendees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventsummary',
            name='summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.Summary'),
        ),
    ]
