# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-06 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0003_auto_20170204_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.CustomUser'),
        ),
    ]
