# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0004_auto_20170312_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagsummary',
            name='num_events',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tagsummary',
            name='summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.Summary'),
        ),
        migrations.AddField(
            model_name='tagsummary',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.Tag'),
        ),
    ]
