# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-07 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0004_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='publication_date',
            field=models.DateField(default=datetime.date.today, verbose_name=b'Date'),
        ),
    ]
