# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0004_auto_20170320_1132'),
        ('aberdeengo', '0002_auto_20170319_1625'),
    ]

    operations = [
    ]
