# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0004_events_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(to='aberdeengo.Tag'),
        ),
    ]
