# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-15 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0005_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='events',
            field=models.ManyToManyField(to='aberdeengo.Event'),
        ),
    ]
