# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0005_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='max_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='sold_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.Ticket'),
        ),
    ]
