# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0005_auto_20170312_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='new_users',
            field=models.IntegerField(default=0),
        ),
    ]
