# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0006_auto_20170405_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
