# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-16 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0006_schedule_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.CustomUser'),
        ),
    ]
