# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0007_auto_20170406_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tickets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.Ticket'),
        ),
    ]
