# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0008_auto_20170216_1332'),
        ('aberdeengo', '0005_event_publication_date'),
    ]

    operations = [
    ]
