# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0009_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tickets',
        ),
        migrations.AddField(
            model_name='ticket',
            name='eventId',
            field=models.IntegerField(default=0),
        ),
    ]
