# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0009_merge'),
        ('aberdeengo', '0006_auto_20170301_2131'),
    ]

    operations = [
    ]
