# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0009_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleentry',
            name='user',
        ),
        migrations.AddField(
            model_name='schedule',
            name='event',
            field=models.ManyToManyField(related_name='something', through='aberdeengo.ScheduleEntry', to='aberdeengo.Event'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.Schedule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.Event'),
        ),
    ]
