# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0010_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(to='aberdeengo.Tag'),
        ),
    ]
