# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0010_auto_20170406_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='eventId',
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.Event'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.CustomUser'),
        ),
    ]
