# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0011_customuser_docfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='docfile',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profilePicture',
            field=models.ImageField(null=True, upload_to=b'pictures/%Y/%m/%d'),
        ),
    ]
