# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0011_auto_20170407_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOccurence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RecurrentEvent',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('aberdeengo.event',),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='times',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventoccurence',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.Event'),
        ),
    ]
