# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-02 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0011_customuser_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='interests',
            new_name='userInterests',
        ),
    ]
