# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0012_auto_20170228_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scheduleentry',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
