# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0012_auto_20170302_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.CustomUser')),
            ],
        ),
    ]
