# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0012_auto_20170412_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.GroupOfEvents'),
        ),
    ]
