# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0013_auto_20170412_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.GroupOfEvents'),
        ),
    ]
