# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0013_auto_20170301_0041'),
        ('aberdeengo', '0011_customuser_interests'),
    ]

    operations = [
    ]
