# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0013_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='score',
        ),
        migrations.AddField(
            model_name='vote',
            name='interestScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='othersScore',
            field=models.IntegerField(default=0),
        ),
    ]
