# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-08 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0014_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='travelType',
            field=models.CharField(default=b'DRIVE', max_length=255),
        ),
    ]
