# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-21 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0014_auto_20170412_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='locationtag',
            name='event',
        ),
        migrations.RemoveField(
            model_name='locationtag',
            name='tag',
        ),
        migrations.AlterField(
            model_name='eventtag',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.Event'),
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='LocationTag',
        ),
    ]
