# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0015_auto_20170421_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('public', models.BooleanField()),
                ('price', models.IntegerField(null=True)),
                ('tags', models.ManyToManyField(to='aberdeengo.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.FloatField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('opentime', models.TimeField(null=True)),
                ('closedtime', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.Location')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.Tag')),
            ],
        ),
        migrations.AlterField(
            model_name='eventtag',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aberdeengo.Events'),
        ),
    ]
