# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-08 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0015_schedule_traveltype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='travelType',
            field=models.CharField(default=b'DRIVING', max_length=255),
        ),
    ]
