# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aberdeengo', '0016_auto_20170308_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='travelType',
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='travelType',
            field=models.CharField(default=b'DRIVING', max_length=255),
        ),
    ]
